"""Persist and restore the latest Monte Carlo simulation snapshot.

The snapshot is generated by this application and stored outside the repository
in the Codespaces home directory, so it survives Streamlit process restarts.
"""

from __future__ import annotations

from pathlib import Path
import pickle
from typing import Any


SNAPSHOT_PATH = Path.home() / ".largestcompany" / "latest_simulation.pkl"


def save_simulation_snapshot(
    *,
    result: Any,
    simulation_inputs: Any,
    run_metadata: dict | None,
    source: str,
) -> Path:
    SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "result": result,
        "simulation_inputs": simulation_inputs,
        "run_metadata": run_metadata or {},
        "source": source,
    }
    temporary_path = SNAPSHOT_PATH.with_suffix(".tmp")
    with temporary_path.open("wb") as handle:
        pickle.dump(payload, handle, protocol=pickle.HIGHEST_PROTOCOL)
    temporary_path.replace(SNAPSHOT_PATH)
    return SNAPSHOT_PATH


def load_simulation_snapshot() -> dict | None:
    if not SNAPSHOT_PATH.exists():
        return None
    try:
        with SNAPSHOT_PATH.open("rb") as handle:
            payload = pickle.load(handle)
    except (OSError, EOFError, pickle.UnpicklingError):
        return None
    required = {"result", "simulation_inputs", "run_metadata", "source"}
    return payload if isinstance(payload, dict) and required.issubset(payload) else None
